services:
  # Backend API (Web Service)
  - type: web
    name: easytrade-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  # Frontend Web App (Static Site)
  - type: web
    name: easytrade-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://easytrade-backend.onrender.com/api # You can update the domain prefix if Render assigns a different random URL
        sync: false
